#!/usr/bin/env bash
#
# Compile shaders/*.{vert,frag} to SPIR-V and refresh the drift checksums.
#
# Run this after editing any GLSL source, then commit the regenerated .spv
# files along with your change. `cargo test -p sicompass` fails if you forget.
#
# The .spv files are committed rather than built by build.rs on purpose:
#
#   - naga, the only pure-Rust GLSL frontend, cannot parse these shaders. It
#     hits `NotImplemented("variable qualifier")` on
#     `layout(binding = 0) uniform sampler2D`, which is how every fragment
#     shader here declares its texture. That is a `//TODO: declaration` in
#     naga's own parser, not something callers can configure around.
#   - Calling glslangValidator from build.rs instead would put a non-Rust tool
#     on the critical path of every build, on four CI runners, in the Nix
#     derivation, and on every contributor's machine, to regenerate ~10 KB of
#     output that changes maybe once a year.
#
# So glslang runs here, by hand, and the committed output is what ships. This
# is the same trade the repository already makes for THIRD-PARTY-LICENSES.html.
#
# glslang comes from the flake dev shell. Run inside `nix develop`, or prefix
# with `nix develop -c`.

set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v glslangValidator >/dev/null 2>&1; then
    echo "error: glslangValidator not found. Run inside 'nix develop'." >&2
    exit 1
fi

# (source, output). The output names are what src/sicompass/src/shaders.rs
# expects.
targets=(
    "text.vert:text_vert.spv"
    "text.frag:text_frag.spv"
    "text_color.frag:text_color_frag.spv"
    "rectangle.vert:rectangle_vert.spv"
    "rectangle.frag:rectangle_frag.spv"
    "image.vert:image_vert.spv"
    "image.frag:image_frag.spv"
)

for t in "${targets[@]}"; do
    src="shaders/${t%%:*}"
    out="shaders/${t##*:}"
    # -V targets Vulkan SPIR-V. --target-env vulkan1.0 keeps the output usable
    # by the Vulkan 1.0 instance render.rs creates, and by MoltenVK on macOS.
    glslangValidator -V --target-env vulkan1.0 "$src" -o "$out"
    echo "  $src -> $out"
done

# Checksums of the GLSL *sources*. The test in src/sicompass/src/shaders.rs
# recomputes these and fails if a source was edited without rerunning this
# script. Checksumming the sources rather than the .spv output is deliberate:
# it catches the mistake we actually care about (stale .spv) without depending
# on glslang producing byte-identical output across versions.
{
    echo "# Generated by scripts/gen-shaders.sh. Do not edit by hand."
    echo "# sha256 of each GLSL source, used by the shader drift test."
    for t in "${targets[@]}"; do
        sha256sum "shaders/${t%%:*}"
    done
} > shaders/CHECKSUMS

echo "Wrote shaders/CHECKSUMS"
