//! SPIR-V shader binaries, embedded from `<workspace>/shaders/*.spv`.
//!
//! These used to be read from `shaders/*.spv` relative to the process working
//! directory. That made the binary non-relocatable: it only started if it
//! happened to be launched from a directory with a `shaders/` tree beside it,
//! which no release archive, installer or package ever provided. Embedding
//! them makes the binary standalone.
//!
//! The `.spv` files are generated by [`scripts/gen-shaders.sh`] and committed.
//! That script's header explains why they are not built by `build.rs`, and
//! [`tests::glsl_sources_match_committed_spirv`] fails if a GLSL source is
//! edited without rerunning it.
//!
//! [`scripts/gen-shaders.sh`]: ../../../../scripts/gen-shaders.sh

macro_rules! shader {
    ($name:ident, $file:literal) => {
        pub const $name: &[u8] = include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../shaders/",
            $file
        ));
    };
}

shader!(TEXT_VERT, "text_vert.spv");
shader!(TEXT_FRAG, "text_frag.spv");
shader!(TEXT_COLOR_FRAG, "text_color_frag.spv");
shader!(RECTANGLE_VERT, "rectangle_vert.spv");
shader!(RECTANGLE_FRAG, "rectangle_frag.spv");
shader!(IMAGE_VERT, "image_vert.spv");
shader!(IMAGE_FRAG, "image_frag.spv");

#[cfg(test)]
mod tests {
    use super::*;

    const ALL: &[(&str, &[u8])] = &[
        ("TEXT_VERT", TEXT_VERT),
        ("TEXT_FRAG", TEXT_FRAG),
        ("TEXT_COLOR_FRAG", TEXT_COLOR_FRAG),
        ("RECTANGLE_VERT", RECTANGLE_VERT),
        ("RECTANGLE_FRAG", RECTANGLE_FRAG),
        ("IMAGE_VERT", IMAGE_VERT),
        ("IMAGE_FRAG", IMAGE_FRAG),
    ];

    /// A truncated or empty blob would otherwise only surface as a Vulkan
    /// error at startup, on whichever machine ran it first.
    #[test]
    fn every_shader_is_valid_spirv() {
        for (name, code) in ALL {
            assert!(!code.is_empty(), "{name} is empty");
            assert_eq!(
                code.len() % 4,
                0,
                "{name} is {} bytes, not a whole number of SPIR-V words",
                code.len()
            );

            // SPIR-V magic number, little-endian.
            let magic = u32::from_le_bytes([code[0], code[1], code[2], code[3]]);
            assert_eq!(
                magic, 0x0723_0203,
                "{name} does not start with the SPIR-V magic number, got {magic:#010x}"
            );
        }
    }

    /// Guards against a `shader!` entry pointing at the wrong file, which
    /// would compile fine and only misrender at runtime.
    #[test]
    fn shaders_are_distinct() {
        for (i, (name_a, a)) in ALL.iter().enumerate() {
            for (name_b, b) in &ALL[i + 1..] {
                assert_ne!(a, b, "{name_a} and {name_b} have identical SPIR-V");
            }
        }
    }

    /// The drift guard: the committed `.spv` files are only correct for the
    /// GLSL they were generated from, and nothing in a normal `cargo build`
    /// would notice a source edit that was never recompiled.
    ///
    /// Checksums the *sources*, not the SPIR-V, so the test does not depend on
    /// glslang producing byte-identical output across versions.
    #[test]
    fn glsl_sources_match_committed_spirv() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../shaders");
        let manifest = std::fs::read_to_string(root.join("CHECKSUMS"))
            .expect("shaders/CHECKSUMS is missing, run scripts/gen-shaders.sh");

        let mut checked = 0;
        for line in manifest.lines() {
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            // `sha256sum` format: "<hex>  <path>", path relative to the
            // workspace root.
            let (expected, path) = line
                .split_once("  ")
                .unwrap_or_else(|| panic!("malformed CHECKSUMS line: {line:?}"));
            let source = root.join(
                std::path::Path::new(path)
                    .file_name()
                    .expect("CHECKSUMS entry has no file name"),
            );
            let bytes = std::fs::read(&source)
                .unwrap_or_else(|e| panic!("reading {}: {e}", source.display()));

            assert_eq!(
                sha256_hex(&bytes),
                expected,
                "{path} has changed since the committed SPIR-V was generated. \
                 Run scripts/gen-shaders.sh and commit the result."
            );
            checked += 1;
        }

        assert_eq!(
            checked,
            ALL.len(),
            "CHECKSUMS covers {checked} sources but there are {} shaders",
            ALL.len()
        );
    }

    /// Minimal SHA-256. Pulling a crate in as a dev-dependency for one test in
    /// a build-tooling guard is not worth the dependency.
    fn sha256_hex(input: &[u8]) -> String {
        const K: [u32; 64] = [
            0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
            0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
            0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
            0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
            0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
            0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
            0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
            0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
            0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
            0xc67178f2,
        ];
        let mut h: [u32; 8] = [
            0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
            0x5be0cd19,
        ];

        let mut msg = input.to_vec();
        let bit_len = (input.len() as u64) * 8;
        msg.push(0x80);
        while msg.len() % 64 != 56 {
            msg.push(0);
        }
        msg.extend_from_slice(&bit_len.to_be_bytes());

        for chunk in msg.chunks(64) {
            let mut w = [0u32; 64];
            for (i, word) in chunk.chunks(4).enumerate() {
                w[i] = u32::from_be_bytes([word[0], word[1], word[2], word[3]]);
            }
            for i in 16..64 {
                let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
                let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
                w[i] = w[i - 16]
                    .wrapping_add(s0)
                    .wrapping_add(w[i - 7])
                    .wrapping_add(s1);
            }

            let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
            for i in 0..64 {
                let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
                let ch = (e & f) ^ ((!e) & g);
                let t1 = hh
                    .wrapping_add(s1)
                    .wrapping_add(ch)
                    .wrapping_add(K[i])
                    .wrapping_add(w[i]);
                let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
                let maj = (a & b) ^ (a & c) ^ (b & c);
                let t2 = s0.wrapping_add(maj);

                hh = g;
                g = f;
                f = e;
                e = d.wrapping_add(t1);
                d = c;
                c = b;
                b = a;
                a = t1.wrapping_add(t2);
            }
            for (dst, src) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
                *dst = dst.wrapping_add(src);
            }
        }

        h.iter().map(|w| format!("{w:08x}")).collect()
    }

    #[test]
    fn sha256_matches_known_vectors() {
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256_hex(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        // Spans a chunk boundary, which the padding loop gets wrong if the
        // `% 64 != 56` condition is off by one.
        assert_eq!(
            sha256_hex(&[b'a'; 1000]),
            "41edece42d63e8d9bf515a9ba6932e1c20cbc9f5a5d134645adb5db1b9737ea3"
        );
    }
}
